dist: xenial
language: bash
services:
  - docker

addons:
  apt:
    packages:
    - jq

jobs:
  include:
    - stage: test
      script:
        - git ls-files --exclude='*Dockerfile' --ignored | xargs --max-lines=1 -I{} sh -c 'docker run --rm -i -v ${PWD}/.hadolint.yaml:/.hadolint.yaml hadolint/hadolint < "$1"' -- {}
        - bash -c 'shopt -s globstar; shellcheck **/*.sh'

    - &build
      stage: Build & update Docker HUB description
      env: VERSION_SHORT=1.0 EXTRA_TAG=latest,stable
      script:
        - ./build.sh $VERSION_SHORT
    - <<: *build
      env: VERSION_SHORT=0.18
    - <<: *build
      env: VERSION_SHORT=0.17
    - <<: *build
      env: VERSION_SHORT=0.16
    - <<: *build
      env: VERSION_SHORT=0.15
    - <<: *build
      env: VERSION_SHORT=0.14
    - <<: *build
      if: branch = master AND type != pull_request
      env:
      script: DOCKERHUB_USERNAME=$DOCKER_USERNAME DOCKERHUB_PASSWORD=$DOCKER_PASSWORD DOCKERHUB_REPOSITORY='factoriotools/factorio' README_FILEPATH='./README.md' ./update-dockerhub-description.sh
