dist: xenial
sudo: required
language: bash
services: 
  - docker

addons:
  apt:
    packages:
    - jq

jobs:
  include:
    - stage: test
      script:
        - git ls-files --exclude='*Dockerfile' --ignored | xargs --max-lines=1 -I{} sh -c 'docker run --rm -i -v ${PWD}/.hadolint.yaml:/.hadolint.yaml hadolint/hadolint < "$1"' -- {}
        - bash -c 'shopt -s globstar; shellcheck **/*.sh'

    - &build
      stage: Build & update Docker HUB description
      env: VERSION_SHORT=0.17 EXTRA_TAG=latest STABLE=0.17.79
      script:
        - ./build.sh $VERSION_SHORT
    - <<: *build
      env: VERSION_SHORT=0.16
    - <<: *build
      env: VERSION_SHORT=0.15
    - <<: *build
      env: VERSION_SHORT=0.14
    - if: branch = master
      script: docker run -v $PWD:/workspace -e DOCKERHUB_USERNAME=$DOCKER_USERNAME -e DOCKERHUB_PASSWORD=$DOCKER_PASSWORD -e DOCKERHUB_REPOSITORY='factoriotools/factorio' -e README_FILEPATH='/workspace/README.md' peterevans/dockerhub-description:2.1.0
